
package wcc.ucm.model.docinfo;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DocInfo", targetNamespace = "http://www.stellent.com/DocInfo/",
                  wsdlLocation =
                  "http://wcc:16200/_dav/cs/idcplg/#%7Bhttp%3A%2F%2Fwww.stellent.com%2FDocInfo%2F%7DDocInfo?wsdl")
public class DocInfo extends Service {

    private final static URL DOCINFO_WSDL_LOCATION;
    private final static WebServiceException DOCINFO_EXCEPTION;
    private final static QName DOCINFO_QNAME = new QName("http://www.stellent.com/DocInfo/", "DocInfo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://wcc:16200/_dav/cs/idcplg/#%7Bhttp%3A%2F%2Fwww.stellent.com%2FDocInfo%2F%7DDocInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCINFO_WSDL_LOCATION = url;
        DOCINFO_EXCEPTION = e;
    }

    public DocInfo() {
        super(__getWsdlLocation(), DOCINFO_QNAME);
    }

    public DocInfo(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCINFO_QNAME, features);
    }

    public DocInfo(URL wsdlLocation) {
        super(wsdlLocation, DOCINFO_QNAME);
    }

    public DocInfo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCINFO_QNAME, features);
    }

    public DocInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocInfo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DocInfoSoap
     */
    @WebEndpoint(name = "DocInfoSoap")
    public DocInfoSoap getDocInfoSoap() {
        return super.getPort(new QName("http://www.stellent.com/DocInfo/", "DocInfoSoap"), DocInfoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocInfoSoap
     */
    @WebEndpoint(name = "DocInfoSoap")
    public DocInfoSoap getDocInfoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.stellent.com/DocInfo/", "DocInfoSoap"), DocInfoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCINFO_EXCEPTION != null) {
            throw DOCINFO_EXCEPTION;
        }
        return DOCINFO_WSDL_LOCATION;
    }

}
